### ISSUE TITLE
Extract track name as well

### ISSUE THREAD

**Issue by innir** [bmewing/gpx#5]
Would be nice to get the name of the tracks as well - probably just output the tracks as named list if names exist.

**Comment by bmewing** [comment]
Do you have an example of a gpx file with track names?

**Comment by innir** [comment]
Most of your test data does have track names ;-)
See e.g. https://github.com/bmewing/gpx/blob/master/tests/testthat/testdata/Bayes_Mountain_Fire_Tower_TN.gpx#L14

Am 2. November 2021 00:57:15 MEZ schrieb Mark Ewing ***@***.***>:

**Comment by innir** [comment]
I'll probably give it a shot this weekend and try to send a PR...
